[build]
  command = "npm run build"
  publish = "client/build"

[[redirects]]
  from = "/api/*"
  to = "https://your-render-api-url.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
